export const PROVINCES: Record<string, string[]> = {
  "NCR": ["Metro Manila"],
  "I": ["Ilocos Norte", "Ilocos Sur", "La Union", "Pangasinan"],
  "III": ["Aurora", "Bataan", "Bulacan", "Nueva Ecija", "Pampanga", "Tarlac", "Zambales"],
  "IV-A": ["Batangas", "Cavite", "Laguna", "Quezon", "Rizal"],
  "V": ["Albay", "Camarines Norte", "Camarines Sur", "Catanduanes", "Masbate", "Sorsogon"],
  "VI": ["Aklan", "Antique", "Capiz", "Guimaras", "Iloilo", "Negros Occidental"],
  "VII": ["Bohol", "Cebu", "Negros Oriental", "Siquijor"],
  "VIII": ["Biliran", "Eastern Samar", "Leyte", "Northern Samar", "Samar", "Southern Leyte"],
  "IX": ["Zamboanga del Norte", "Zamboanga del Sur", "Zamboanga Sibugay"],
  "X": ["Bukidnon", "Camiguin", "Lanao del Norte", "Misamis Occidental", "Misamis Oriental"],
  "XI": ["Davao de Oro", "Davao del Norte", "Davao del Sur", "Davao Occidental", "Davao Oriental"],
  "XII": ["Cotabato", "Sarangani", "South Cotabato", "Sultan Kudarat"],
  "XIII": ["Agusan del Norte", "Agusan del Sur", "Dinagat Islands", "Surigao del Norte", "Surigao del Sur"],
  "BARMM": ["Basilan", "Lanao del Sur", "Maguindanao", "Sulu", "Tawi-Tawi"],
  "CAR": ["Abra", "Benguet", "Ifugao", "Kalinga", "Mountain Province"],
  "II": ["Batanes", "Cagayan", "Isabela", "Nueva Vizcaya", "Quirino"],
  "IV-B": ["Marinduque", "Occidental Mindoro", "Oriental Mindoro", "Palawan", "Romblon"],
};
